name: Colin's Blog
url: cnarans.github.io
description: Look at the pretty colors

permalink: mysite/:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
