name: Colin's Blog
url: cnarans.github.io/mysite
description: Look at the pretty colors

permalink: /:title
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
